/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alerts: typeof import('./src/components/Alerts.vue')['default']
    ChampionAutocomplete: typeof import('./src/components/ChampionAutocomplete.vue')['default']
    copy: typeof import('./src/components/Home copy.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Matchups: typeof import('./src/components/Matchups.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
